### ISSUE TITLE
LiteLoader plugin: litemod output not fully obfuscated

### ISSUE THREAD

**Issue by octylFractal** [MinecraftForge/ForgeGradle#148]
Using the LL plugin leaves you with a bad jar that only works with the help of runtime deobfuscation by Forge because the code is in searge names.

Data collected so far:

``` yml
# Format: 
# appliedfirst:
#     appliedsecond:
#         result:
# good means that the jar is fully obf'd
# bad means that the jar only works with runtime deobf (searge names)
#
# please note that this is tested with a Minecraft-only dependent code base,
# so can be compiled any way possible.
FML:
  none:
    result: "Bad -fml.jar"
  LiteLoader:
    result: "Bad -fml.jar, good -liteloader.litemod"
  Forge:
    result: "Not possible, Forge cannot overlay"
LiteLoader:
  none:
    result: "Bad .litemod"
  FML:
    result: "Not possible, FML cannot overlay"
  Forge:
    result: "Not possible, Forge cannot overlay"
Forge:
  none:
    result: "Bar .jar"
  LiteLoader:
    result: "Bad -forge.jar, good -liteloader.litemod"
  FML:
    result: "Not possible, FML cannot overlay"

```

The triple combos are not tested, but the results are not possible because each one involves applying Forge + FML which is not possible.

This data indicates that for some reason, when there is one project, it treats it as Forge/FML and only does partial obfuscation, which is OKAY for Forge/FML as they use runtime deobf and it doesn't matter in the end but not okay for LL as there is no deobf.
